apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-account-manager.fullname" . }}-env
  labels:
    {{- include "ldap-account-manager.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.extraEnv }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
  {{- end }}
